[package]
name = "selfblog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maud = "0.23.0"
clap = { version = "3.2.5", features = ["derive"] }
log = "0.4.17"
env_logger = "0.9.0"