[package]
name = "selfblog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
actix-web = { version = "4.1.0", features = ["rustls"] }
actix-files = "0.6.2"
tokio = { version = "1.21.0", features = ["full"] }
rustls = "0.20.6"
rustls-pemfile = "1.0.1"