[package]
name = "selfblog-cli"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "selfblog-server"
version = "0.0.0"
edition = "2021"
path = "src/server.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
pulldown-cmark = "0.9.1"
clap = { version = "3.2.5", features = ["derive"] }
log = "0.4.17"
env_logger = "0.9.0"
figment = { version = "0.10", features = ["env", "toml", "json"] }
anyhow = "1.0.58"
daemonize = "0.4.1"
rocket = "0.5.0-rc.2"
tokio = { version = "1.19.2", features = ["full"] }
serde = "1.0.137"
dirs = "4.0.0"
serde_derive = "1.0.137"
toml = "0.5.9"
derive_more = { version = "0.99.17", default-features = true }